#!/bin/bash
{ set +x; } 2>/dev/null
source_dir="$( cd -P "$( dirname "$0" )" >/dev/null 2>&1 && pwd )"
root_dir=$(cd $source_dir && cd ../ && pwd)
cd $root_dir
source script/helpers/_utils.sh

if ! type dotnet > /dev/null; then
    fatal "dotnet is not installed. Please install it from https://dotnet.microsoft.com"
fi

echo "You're good to go!"